version: '3'
services:
  app:
    container_name: app
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    # devices: # work on linux maybe
    #   - /dev/video1:/dev/video1
    command: python main.py
    privileged: true
    

